### PR TITLE
Fixes for region capture issues

### LINKED ISSUE #1031: Crash when triggering a "capture region" with hotkey
**Describe the bug**
Crash and subusequent error window when triggering a "capture region" with hotkey

**To Reproduce**
Example steps to reproduce the behavior:
1. press "capture region" hotkey (CTRL + SHIFT + S in my case)
2. See Error window appear with "Sorry, an unexpected error occurred..."

**Expected behavior**
No crash

**Screenshots**

**Versions (please complete the following information):**
Software version: 1.3.300 - c1ad1d4a93 (64 bit)
.NET runtime version: 4.0.30319.42000+
Time: 2026-03-04 14:04:15 -08:00
OS: Windows 10 2009 x64 build 19045
GDI object count: 96
User object count: 47

Exception: System.ArgumentException
Message: Parameter is not valid.

Stack:
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at Greenshot.Base.Core.ImageHelper.CreateEmpty(Int32 width, Int32 height, PixelFormat format, Color backgroundColor, Single horizontalResolution, Single verticalResolution)
   at Greenshot.Base.Core.WindowCapture.CaptureRectangle(NativeRect captureBounds)
   at Greenshot.Base.Core.WindowCapture.CaptureRectangle(ICapture capture, NativeRect captureBounds)
   at Greenshot.Base.Core.WindowCapture.CaptureScreen(ICapture capture)
   at Greenshot.Helpers.CaptureHelper.MakeCapture()
   at Greenshot.Helpers.CaptureHelper.CaptureRegion(Boolean captureMouse)
   at Greenshot.Base.Controls.HotkeyControl.HandleMessages(Message& m)
   at Greenshot.Forms.MainForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Configuration dump:

**Additional context**

---
**Stack Trace Hash:** [443fe1b66ea6]

### PR DESCRIPTION
**Pull request by danrhodes**
Fixes #1031 #1153 #1019, which I have grouped together as they are all "region capture" issues.

**Fix 1 — ArgumentException in Bitmap..ctor: degenerate DIB dimensions**
**File: WindowCapture.cs:357-363**

**What was wrong**: Inside the offscreenContent branch, Image.FromHbitmap(safeDibSectionHandle.DangerousGetHandle()) was called to get tmpBitmap, then its .Width and .Height were passed directly to ImageHelper.CreateEmpty. Under two known conditions — a multi-monitor setup where the virtual desktop rectangle spans monitors at mixed DPI scales, or a transient GDI resource exhaustion (session lock/unlock, high GDI object counts) — the DIB section handle can produce a bitmap with zero or invalid dimensions. new Bitmap(0, height, format) throws ArgumentException: Parameter is not valid, which was unhandled and crashed the capture.

**What was fixed**: A guard was added immediately after tmpBitmap is loaded. If either dimension is <= 0, we log the degenerate state, fall back to returning the raw DIB bitmap (same path as the non-offscreen branch), and break out successfully. The transparent compositing is skipped in this edge case — a minor visual trade-off (no transparency in inter-monitor gaps) versus a hard crash.

Additionally, the retry loop's catch block was widened to also catch ArgumentException. Previously, only ExternalException was retried; any ArgumentException escaping the offscreenContent block went straight to the unhandled exception handler. Now it's wrapped and treated as a retryable failure, giving the loop its three attempts before giving up.

**Fix 2 — ArgumentNullException in Monitor.Enter: race between Dispose and background thread
File: CaptureHelper.cs:96**

**What was wrong**: MakeCapture starts a background thread (RetrieveWindowDetails) that uses lock (_windows) to safely add entries to the list. Dispose — called via the using block when MakeCapture returns or throws — was setting _windows = null. If Dispose ran between the moment the background thread read _windows as a non-null reference and the moment it entered the lock, Monitor.Enter received null and threw ArgumentNullException. This is a classic TOCTOU race: the thread sees a non-null _windows, then Dispose nulls it, then the thread calls lock on the now-null reference.

The Join() call at the end of MakeCapture was supposed to prevent this — but if MakeCapture exited via an exception (e.g., Crash A happening first), the Join() still ran, but an exception from CaptureWithFeedback or CaptureScreen could skip execution flow in ways that cause Dispose to fire before the join completes cleanly. The two crash entries from the same user 33 seconds apart (23:50:42 and 23:51:15) confirm this sequence: Crash A fires first, then Crash B follows as the teardown races the background thread.

**What was fixed**: _windows = null was removed from Dispose. The List<WindowDetails> is not an unmanaged resource — it doesn't need explicit nulling for correctness. The background thread's lifetime is already managed by the Join() in MakeCapture. Leaving _windows alive until the GC collects CaptureHelper is entirely safe, and the comment explains why to prevent the null-on-dispose pattern from being reintroduced.

**Fix 3 — ArgumentException defensive guard in ImageHelper.CreateEmpty
File: ImageHelper.cs:1360-1363**

**What was wrong**: CreateEmpty passed width and height straight to new Bitmap(...) with no validation. System.Drawing.Bitmap accepts only positive dimensions; anything <= 0 throws ArgumentException: Parameter is not valid with no indication of what the invalid values actually were. Since CreateEmpty is called from multiple sites across the codebase (torn edges, shadows, borders, resize, rotation), any caller passing bad geometry produced the same opaque exception with no diagnostic information.

**What was fixed**: An explicit guard was added at the top of CreateEmpty. If either dimension is non-positive, it throws ArgumentException with the actual values in the message (Cannot create a bitmap with non-positive dimensions (0x480)). This means:

Any future call site that passes bad dimensions gets a clear, diagnosable error message in the log instead of a cryptic GDI+ failure.

**Fix 1's path now benefits doubly**: if the degenerate-dimension guard in WindowCapture were ever bypassed (e.g. a new call site added in future), the error would still surface with a useful message and be caught by the widened retry loop rather than crashing the process.

### CODE REVIEW

File: src/Greenshot.Base/Core/WindowCapture.cs [hunk 1]
```diff
@@ -354,6 +354,13 @@ public static Bitmap CaptureRectangle(NativeRect captureBounds)
                         if (offscreenContent)
                         {
                             using Bitmap tmpBitmap = Image.FromHbitmap(safeDibSectionHandle.DangerousGetHandle());
+                            if (tmpBitmap.Width <= 0 || tmpBitmap.Height <= 0)
+                            {
+                                Log.Warn($"DIB section returned degenerate bitmap dimensions ({tmpBitmap.Width}x{tmpBitmap.Height}), skipping offscreen capture.");
+                                returnBitmap = Image.FromHbitmap(safeDibSectionHandle.DangerousGetHandle());
```
Comment (Lakritzator) [inline src/Greenshot.Base/Core/WindowCapture.cs]: Why not take the tmpBitmap created on line 356 to return (remove the using keyword) and after the if/break use a using block? Prevents 2x Image.FromHbitmap?
So:

```
using (tmpBitmap) {
    returnBitmap = ImageHelper.CreateEmpty(tmpBitmap.Width, tmpBitmap.Height, PixelFormat.Format32bppArgb, Color.Transparent, tmpBitmap.HorizontalResolution, tmpBitmap.VerticalResolution);
}
```

**Comment by Lakritzator** [comment]
Again very impressing work ❤️

**Comment by danrhodes** [comment]
> Again very impressing work ❤️

Thanks,

Happy to help where I can 👍

**Comment by danrhodes** [comment]
@Lakritzator - Good catch on the double Image.FromHbitmap call — updated to remove the using from the declaration and reuse tmpBitmap directly as returnBitmap in the early-exit path, with the using block wrapping the CreateEmpty + draw loop instead.

While looking at this, I noticed the else branch (non-offscreen path, line 384) was calling Image.FromHbitmap with no dimension check at all — so a degenerate DIB there would silently return a 0×0 bitmap to the caller and crash outside the retry loop. The if branch got the guard, but the else was missed, so I've added a matching check there too.

**Review by Lakritzator — APPROVED** [review]
